runtime: nodejs12
instance_class:

env_variables:
    DBURL: mongodb+srv://Bharat:abcBharat@cluster0.muuox.mongodb.net/prod?retryWrites=true&w=majority

    CLIENT_URL: 'https://nginx-logger.netlify.app'
    REFRESH_TOKEN_SECRET: aklngkla677
    ACCESS_TOKEN_SECRET: djaghajhdfhal68
    ADMIN_TOKEN_SECRET: admingtoken123@#jk
    BCRYPT_SALT: 5
    NODE_ENV: development
    SERVER_URL: '/'


handlers:
    #
    - url: /api/.*
      secure: always
      script: auto

    - url: /(.*\..+)$
      secure: always
      static_files: dist/build/\1
      upload: dist/build/(.*\..+)$

    - url: /.*
      secure: always
      static_files: dist/build/index.html
      upload: dist/build/index.html
